// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using healthcare.Repositorio.Contexto;

namespace healthcare.Repositorio.Migrations
{
    [DbContext(typeof(HealthCareContexto))]
    partial class HealthCareContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("healthcare.Dominio.Entidades.Consultorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("healthcare.Dominio.Entidades.ConsultorioMedico", b =>
                {
                    b.Property<int>("ConsultorioId");

                    b.Property<int>("MedicoId");

                    b.Property<int>("Id");

                    b.HasKey("ConsultorioId", "MedicoId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("ConsultorioMedico");
                });

            modelBuilder.Entity("healthcare.Dominio.Entidades.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Telefone")
                        .HasMaxLength(50);

                    b.Property<decimal>("ValorConsulta")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("healthcare.Dominio.Entidades.ConsultorioMedico", b =>
                {
                    b.HasOne("healthcare.Dominio.Entidades.Consultorio", "Consultorio")
                        .WithMany("ConsultorioMedicos")
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("healthcare.Dominio.Entidades.Medico", "Medico")
                        .WithMany("ConsultorioMedicos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
